name: Go Sec

on:
  pull_request:
    branches: [ main ]

jobs:
  gosec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download

      - name: Run gosec
        uses: securego/gosec@master
        with:
          # Path to the directory containing the Go source files to analyze
          path: ./
          # Output format: text, json, yaml, or sonarqube
          output: text
          # Severity level (0-3): 0=low, 1=medium, 2=high, 3=critical
          severity: 1
