name: Generate Swag Documentation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate Swag Documentation
        run: |
          ls -al
          swag init -g cmd/auth/main.go
          ls -al
      - name: Commit and push updated Swagger docs
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update Swagger Documentation"
          if ! git diff --exit-code main origin/main --quiet; then
            git diff
            echo "No changes detected in Swagger docs. Skipping push."
          else
            git push origin main
          fi
        working-directory: ./docs


