name: Go Vet

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Go vet
        uses: actions-go/go-vet@v1
