name: Go Vet

on:
  pull_request:
    branches: [ main ]

jobs:
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go vet
        uses: conventional-actions/go-vet@v1
